- name: install grafana
  yum:
    name: https://s3-us-west-2.amazonaws.com/grafana-releases/release/grafana-{{ version }}-1.x86_64.rpm
    state: latest


- name: "grafana configuration file copy"
  template:
    src: "grafana.conf.j2"
    dest: /etc/grafana/grafana.ini
  notify: event_restart_grafana

- name: "grafana server started"
  service:
    name: grafana-server
    enabled: true
    state: started

- name: "check if grafana is accessible"
  url:
    url: http://127.0.0.1:3000
    method: GET
    status_code: 200